version: "4"

services:
  mysql-cardapio:
    image: mysql:8.3.0
    container_name: cardapio-database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysql} # Usar variável de ambiente
    ports:
      - "3307:3306" # Mapear a porta 3306 do MySQL para 3307 no host
    volumes:
      - ./mysql:/var/lib/mysql # Persistência de dados
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql # Iniciar com SQL de configuração
  backend-cardapio:
    build: ./service
    container_name: backend-cardapio
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - mysql-cardapio
    restart: unless-stopped